import { createTheme } from "@mui/material";

export const theme = createTheme({
  palette: {
    mode: "light",
    primary: {
      main: "#00355f",
      contrastText: "#ffffff",
      dark: "#001c37",
      light: "#0f4c81",
    },
    secondary: {
      main: "#006b5f",
      contrastText: "#ffffff",
      light: "#62fae3",
      dark: "#005047",
    },
    tertiary: {
      main: "#313436",
      contrastText: "#ffffff",
      light: "#474b4d",
    },
    error: {
      main: "#ba1a1a",
      contrastText: "#ffffff",
      light: "#ffdad6",
      dark: "#93000a",
    },
    background: {
      default: "#f8f9ff",
      paper: "#ffffff",
    },
    text: {
      primary: "#0b1c30",
      secondary: "#42474f",
    },
    divider: "#c2c7d1",
    action: {
      hover: "rgba(0, 53, 95, 0.06)",
      selected: "rgba(0, 53, 95, 0.1)",
      focus: "rgba(0, 53, 95, 0.16)",
    },
    precision: {
      surface: "#f8f9ff",
      surfaceDim: "#cbdbf5",
      surfaceBright: "#f8f9ff",
      surfaceContainerLowest: "#ffffff",
      surfaceContainerLow: "#eff4ff",
      surfaceContainer: "#e5eeff",
      surfaceContainerHigh: "#dce9ff",
      surfaceContainerHighest: "#d3e4fe",
      onSurface: "#0b1c30",
      onSurfaceVariant: "#42474f",
      inverseSurface: "#213145",
      inverseOnSurface: "#eaf1ff",
      outline: "#727780",
      outlineVariant: "#c2c7d1",
      surfaceTint: "#2d6197",
      primaryContainer: "#0f4c81",
      onPrimaryContainer: "#8ebdf9",
      inversePrimary: "#a0c9ff",
      secondaryContainer: "#62fae3",
      onSecondaryContainer: "#007165",
      tertiaryContainer: "#474b4d",
      onTertiaryContainer: "#b8bbbc",
      primaryFixed: "#d2e4ff",
      primaryFixedDim: "#a0c9ff",
      onPrimaryFixed: "#001c37",
      onPrimaryFixedVariant: "#07497d",
      secondaryFixed: "#62fae3",
      secondaryFixedDim: "#3cddc7",
      onSecondaryFixed: "#00201c",
      onSecondaryFixedVariant: "#005047",
      tertiaryFixed: "#e0e3e5",
      tertiaryFixedDim: "#c4c7c9",
      onTertiaryFixed: "#191c1e",
      onTertiaryFixedVariant: "#444749",
      surfaceVariant: "#d3e4fe",
    },
  },
  typography: {
    fontFamily: '"Manrope", "Inter", "Segoe UI", sans-serif',
    h1: {
      fontFamily: '"Manrope", "Inter", "Segoe UI", sans-serif',
      fontSize: "48px",
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: "-0.02em",
    },
    h2: {
      fontFamily: '"Manrope", "Inter", "Segoe UI", sans-serif',
      fontSize: "36px",
      fontWeight: 700,
      lineHeight: 1.2,
      letterSpacing: "-0.01em",
    },
    h3: {
      fontFamily: '"Manrope", "Inter", "Segoe UI", sans-serif',
      fontSize: "24px",
      fontWeight: 600,
      lineHeight: 1.3,
      letterSpacing: 0,
    },
    body1: {
      fontSize: "16px",
      fontWeight: 400,
      lineHeight: 1.6,
      letterSpacing: 0,
    },
    body2: {
      fontSize: "14px",
      fontWeight: 400,
      lineHeight: 1.5,
      letterSpacing: 0,
    },
    button: {
      fontSize: "16px",
      fontWeight: 600,
      lineHeight: 1,
      letterSpacing: "0.01em",
      textTransform: "none",
    },
    bodyLg: {
      fontSize: "18px",
      fontWeight: 400,
      lineHeight: 1.6,
      letterSpacing: 0,
    },
    labelCaps: {
      fontSize: "12px",
      fontWeight: 700,
      lineHeight: 1,
      letterSpacing: "0.05em",
      textTransform: "uppercase",
    },
  },
  shape: {
    borderRadius: 8,
    rounded: {
      sm: "0.25rem",
      default: "0.5rem",
      md: "0.75rem",
      lg: "1rem",
      xl: "1.5rem",
      full: "9999px",
    },
  },
  spacing: 8,
  shadows: [
    "none",
    "0px 4px 20px rgba(0, 0, 0, 0.05)",
    "0px 10px 30px rgba(0, 0, 0, 0.08)",
    "0px 12px 34px rgba(0, 0, 0, 0.1)",
    ...Array(21).fill("0px 16px 40px rgba(0, 0, 0, 0.12)"),
  ],
  components: {
    MuiCssBaseline: {
      styleOverrides: {
        ":root": {
          "--color-surface": "#f8f9ff",
          "--color-surface-dim": "#cbdbf5",
          "--color-surface-bright": "#f8f9ff",
          "--color-surface-container-lowest": "#ffffff",
          "--color-surface-container-low": "#eff4ff",
          "--color-surface-container": "#e5eeff",
          "--color-surface-container-high": "#dce9ff",
          "--color-surface-container-highest": "#d3e4fe",
          "--color-on-surface": "#0b1c30",
          "--color-on-surface-variant": "#42474f",
          "--color-inverse-surface": "#213145",
          "--color-inverse-on-surface": "#eaf1ff",
          "--color-outline": "#727780",
          "--color-outline-variant": "#c2c7d1",
          "--color-surface-tint": "#2d6197",
          "--color-primary": "#00355f",
          "--color-on-primary": "#ffffff",
          "--color-primary-container": "#0f4c81",
          "--color-on-primary-container": "#8ebdf9",
          "--color-secondary": "#006b5f",
          "--color-on-secondary": "#ffffff",
          "--color-secondary-container": "#62fae3",
          "--color-on-secondary-container": "#007165",
          "--space-xs": "4px",
          "--space-sm": "12px",
          "--space-md": "24px",
          "--space-lg": "48px",
          "--space-xl": "80px",
          "--container-max": "1280px",
          "--gutter": "24px",
          "--radius-sm": "0.25rem",
          "--radius": "0.5rem",
          "--radius-md": "0.75rem",
          "--radius-lg": "1rem",
          "--radius-xl": "1.5rem",
          "--radius-full": "9999px",
          "--shadow-level-1": "0px 4px 20px rgba(0, 0, 0, 0.05)",
          "--shadow-level-2": "0px 10px 30px rgba(0, 0, 0, 0.08)",
        },
        html: {
          height: "100%",
        },
        body: {
          backgroundColor: "#f8f9ff",
          color: "#0b1c30",
          fontFamily: '"Manrope", "Inter", "Segoe UI", sans-serif',
          height: "100%",
        },
        "#root": {
          height: "100%",
        },
      },
    },
    MuiButton: {
      styleOverrides: {
        root: {
          borderRadius: "0.5rem",
          minHeight: 44,
          paddingInline: 20,
        },
        containedPrimary: {
          boxShadow: "none",
          "&:hover": {
            boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.05)",
          },
        },
        outlined: {
          borderColor: "#c2c7d1",
        },
      },
    },
    MuiCard: {
      styleOverrides: {
        root: {
          borderRadius: "1rem",
          boxShadow: "0px 4px 20px rgba(0, 0, 0, 0.05)",
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: {
          borderRadius: "9999px",
          fontWeight: 700,
        },
      },
    },
    MuiOutlinedInput: {
      styleOverrides: {
        root: {
          borderRadius: "0.5rem",
          backgroundColor: "#ffffff",
          "& .MuiOutlinedInput-notchedOutline": {
            borderColor: "#c2c7d1",
          },
          "&.Mui-focused .MuiOutlinedInput-notchedOutline": {
            borderColor: "#00355f",
          },
        },
      },
    },
  },
});
